<?php

namespace core\user\controllers;

use core\base\exceptions\DbException;
use core\base\exceptions\RouteException;

class ProductController extends BaseUser
{
    /**
     * @throws RouteException
     * @throws DbException
     */
    protected function inputData()
    {
        parent::inputData(); // TODO: Change the autogenerated stub
        if (empty($this->parameters['alias'])) {
            throw new RouteException('Отсутствует ссылка на товар');
        }
        $data = $this->model->getGoods([
            'where' => ['alias' => $this->parameters['alias'], 'visible' => 1]
        ]);
        if (!$data) {
            throw new RouteException("Отсутствует товар по ссылке {$this->parameters['alias']}");
        }
        $data = array_shift($data);
        $deliveryInfo = $this->model->get('information', [
            'where' => ['visible' => 1, 'name' => 'доставка', ' name' => 'оплата'],
            'operand' => ['=','%LIKE%'],
            'limit' => 1
        ]);
        $deliveryInfo && $deliveryInfo = array_shift($deliveryInfo);
        return compact('data', 'deliveryInfo');
    }
}