<?php

namespace core\user\controllers;

use core\user\model\Model;

class SearchController extends BaseUser
{
    protected function inputData()
    {
        parent::inputData(); // TODO: Change the autogenerated stub
        $goods = $this->search();
        $this->template = TEMPLATE . 'catalog';
        $data['name'] = 'Результаты поиска ' . (!empty($_GET['search']) ? 'по запросу <i>' . $_GET['search'] . '</i>' : '');
        $dontShowAside = true;
        return  compact('goods', 'data', 'dontShowAside');
    }
    public function search() {
        !$this->model && $this->model = Model::instance();
        $search = $this->clearStr( $_GET['search'] ?? '' );
        $data = [];
        if ($search) {
            $goodsIds = $this->model->searchGoodsIds($search);
            if ($goodsIds) {
                $data = $this->model->getGoods([
                    'where' => ['id' => $goodsIds],
                    'operand' => ['IN']
                ]);
            }
        }
        return $data;
    }
}